### ISSUE TITLE
Places being categorised as Unknown country

### ISSUE THREAD

**Issue by metaben** [elliotchance/gedcom#143]
I've got a surprising number of Places categorised as Unknown country.

Example in the raw data:

1 RESI
2 DATE 1935
2 PLAC 15 Onapu Rd, Wellington, New Zealand
2 OBJE @M2125@

and:

1 BIRT
2 DATE 21 JAN 1890
2 PLAC Barbados

**Comment by elliotchance** [comment]
The country (and other jurisdictional entities) are tricky because at the moment I rely on the document to follow the GEDCOM standard for place formats. The place must be in the form of "Name,County,State,Country". [1]

Strictly speaking what you have is valid, but a more parsable GEDCOM stream would contain a FORM that describes the jurisdictional entities to separate the place name (which is really just a text label):

```
1 RESI
2 DATE 1935
2 PLAC 15 Onapu Rd, Wellington, New Zealand
3 FORM 15 Onapu Rd,,Wellington,New Zealand
2 OBJE @M2125@
```

and

```
1 BIRT
2 DATE 21 JAN 1890
2 PLAC Barbados
3 FORM ,,,Barbados
```

In reality this isn't a permanent solution because so many programs don't follow the rules. I want my library to be much more intuitive and adaptable.

I have thought of this before and likely the best solution is to simply have a list of countries (current and historical) that are checked against the suffix of the place name. If one is found then this is assumed to be the country. This could not extent to other sub-jurisdictional entities like State or County but they are often less relevant anyway to the country.

[1] https://godoc.org/github.com/elliotchance/gedcom#PlaceNode.JurisdictionalName

**Comment by metaben** [comment]
What you've done is a good compromise!
