### ISSUE TITLE
gedcomdiff - open : The system cannot find the file specified

### ISSUE THREAD

**Issue by nev7n** [elliotchance/gedcom#194]
Running v31.1.11 gedcomdiff binary on windows gives an error...

``PS H:\ancestry\ged> .\gedcomdiff -left-gedcom left.ged -right-gedcom right.ged -sort written-name
2019/01/05 09:06:21 open : The system cannot find the file specified.``

Both left.ged and right.ged exist in the current directory

Also note that -sort is required although this isn't indicated in -help

**Comment by elliotchance** [comment]
I can see from the error that the path is blank (although I admit thats not entirely obvious). My first guess would be that the args are being parsed differently on windows.

I know on Mac I can use the syntax `-left-gedcom left.ged` and `-left-gedcom=left.ged`. What happens if you try with `=`?

The sort should be optional: #196

Sorry, I do not have a windows machine around anywhere.

**Comment by nev7n** [comment]
I ran the tool in the debugger.  

The problem was that I hadn't specified the -output parameter so it was trying to create an output file called "" and failing.

So a case of user error, but a nicer error message would be good :)

Working great now - nice tool, thanks

**Comment by elliotchance** [comment]
Thanks for that. I will fix these things in a PR soon.
