### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by BryanBentz** [elliotchance/gedcom#274]
When reading in my main file, it seems a reference caused a parsing problem:

"2019/05/07 11:33:15 line 332070: could not parse: MyHeritage.com [online database]. Lehi, UT, USA: MyHeritage (USA) Inc."

FYI, and it may be key, I use Family Tree Maker for Windows as my main program, and did an export to GEDCOM.  It's possible its export includes special characters, etc., which may be the problem.
(If I had some further info about where this parse problem occurred, e.g., person id, or name, I could fix such things via hand editing).
Or, maybe there's just something off in the reference parsing.

**Comment by elliotchance** [comment]
This is a bug in Family Tree Maker that I have also seen in other applications. Basically, the file is encoded incorrectly because the newline that is the name of the reference is not being escaped correctly.

As you said, this can be fixed by removing the new lines from the reference and re-exporting the GEDCOM. However, this is a big enough problem that gedcom provides a stable way to recover from these errors by enabling `AllowMultiLine`.

Which binary/application are you trying to use this gedcom file with?

Technical detail: https://github.com/elliotchance/gedcom/blob/master/decoder.go#L39-L49

**Comment by cbrunnkvist** [comment]
Yup I got this error too,

```
2 PLAC Herkulsberga by
2 NOTE Herkeberga församling, Lagunda kontrakt
Födelse och dopbok, bild 25 1898-1920
1 BURI Gravplats xxxx
```

for data containing a newline. Is it really that illegal in GEDCOM? I'm not sure where this file originated from: it's exported from either Ancectry.com or MyHeritage.com and has been able to move data between them.

**Comment by elliotchance** [comment]
As far as I'm aware this is not valid GEDCOM. Here's an example of an extreme case. The follow on line looks like a new node because of the `1` (maybe from a list, or just a general note):

```gedcom
4 CONC Book:
1 reference in Country:SwedenBook:....
```

A parser would interpret this as two nodes:

- 4 `CONC` "Book:"
- 1 `reference` "in Country:SwedenBook:...."

When actually it should be understood as a single node:

- 4 CONC "Book:\n1 reference "in Country:SwedenBook:...."

That being said, there are so many applications out there that don't handle edge cases properly, so everyone's had to adapt by allowing failures like this and moving on.

I'm going to close this issue because I belive `-allow-multi-line` resolves the issue.
