### ISSUE TITLE
GEDCOM 5.5.5. support

### ISSUE THREAD

**Issue by fbaube** [elliotchance/gedcom#284]
Version 5.5.5 of GEDCOM is being sold as a major clean-up and simplification. Supporting it might result in less code, not more.

**Comment by elliotchance** [comment]
Can you elaborate more? Have you found a GEDCOM file that is incompatible?

**Comment by fbaube** [comment]
GEDCOM 5.5.5 files are by design backward-compatible with GEDCOM 5.5.1 applications. 
There is a good overview of technical aspects here: https://www.tamurajones.net/GEDCOM555JustARevision.xhtml

**Comment by elliotchance** [comment]
Thanks for the information. The GEDCOM standard is so huge and complex that the goal with this project is not to support every feature, but rather implement parts of the standard and fix bugs as required.

I'll close this issue because there is nothing specific to be done here. Of course, if you do find a bug with any GEDCOM version please open a new issue.

**Comment by fbaube** [comment]
Fair enough
