### ISSUE TITLE
Age estimations/calculations not showing

### ISSUE THREAD

**Issue by metaben** [elliotchance/gedcom#295]
This might be a bug - ages might not have been calculated here? This is in the dataset I provided for #276.

![image](https://user-images.githubusercontent.com/8319271/73218552-1abdee00-4152-11ea-9a00-31adb8e38c53.png)

**Comment by elliotchance** [comment]
At first glance that does look like a bug because the Birth seems valid. The Ages are calculated based on the _estimated birth date_ which can be a combination of birth and baptism. I'll investigate with the existing data set you have provided.

On a side note, the Residence in 1901 should be after the Baptism. I'll also look into that - perhaps that's related.
